version: '3.8'

services:
  battery-forecast-engine:
    build: .
    container_name: battery_forecast_engine
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_PORT=8000
      - APP_HOST=0.0.0.0
    volumes:
      - .:/app
    restart: unless-stopped
