version: '3.8'

services:
  voltpulse-scada:
    build: .
    container_name: voltpulse_ai_scada
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
