[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::UserWarning
    ignore:.*Using `httpx` with `starlette.testclient`.*
    ignore:.*StarletteDeprecationWarning.*
